pipeline {
	agent any

	//Configure the following environment variables before executing the Jenkins Job
	environment {
		IntegrationFlowID = "com.nmbs.if.CS.CPI2EMS.I0001.Customer.Create_Update"
		ConfigParameter = "SAP_Receiver"
		NewConfigValue = "TEST_GCP"
		CPIHost = "d4854fbatrial.it-cpitrial05.cfapps.us10-001.hana.ondemand.com"
		CPIOAuthHost = "d4854fbatrial.authentication.us10.hana.ondemand.com"
		CPIOAuthCredentials = "${env.CPI_OAUTH_CRED}"
    }
	
	stages {
		stage('Update Configuration') {
			steps {
				script {
				   //Get oauth token
				   def token;
				   println('Fetching authentification token')
				   try {
					def getTokenResp = httpRequest acceptType: 'APPLICATION_JSON', 
						//authentication: "${env.CPIOAuthCredentials}", 
						customHeaders:[[name:'Authorization', value:"Basic c2ItM2JjNGRhMGMtN2E0YS00ZTc0LWE0MDEtNDc3NzY1NTExYzM1IWIyNzkwNDR8aXQhYjI2NjU1OmQwZDRjZjFiLWI5MTUtNDI5Ny1iOWJjLTEzYTI0ZWQwMmFhNyRfeUNDSi1tdE5lOWE3V041aWRKSkU1T216T2JuRFdoM3AxS0ZEb01VaWd3PQ=="]],
						contentType: 'APPLICATION_JSON', 
						httpMode: 'POST', 
						consoleLogResponseBody : 'true',
						responseHandle: 'LEAVE_OPEN', 
						timeout: 30, 
						url: 'https://' + env.CPIOAuthHost + '/oauth/token?grant_type=client_credentials';
					def jsonObjToken = readJSON text: getTokenResp.getContent()
					token = "Bearer " + jsonObjToken.access_token
			        } catch (Exception e) {
						error("Oauth bearer token generation failed:\n${e}")
					}

					println('Bearer token fetched => ' + token)
					//get the list of config parameters
					def getConfigResp = httpRequest acceptType: 'APPLICATION_JSON', 
						customHeaders: [[maskValue: false, name: 'Authorization', value: token]], 
						httpMode: 'GET', 
						ignoreSslErrors: false, 
						responseHandle: 'LEAVE_OPEN', 
						timeout: 30, 
						url: 'https://' + "${env.CPIHost}" + '/api/v1/IntegrationDesigntimeArtifacts(Id=\'' + "${env.IntegrationFlowID}" + '\',Version=\'active\')/Configurations';
				
					def jsonObj = readJSON text: getConfigResp.content;
					def configParameterExist;
					println("----------listing old config----------");
					jsonObj.d.results.each {
						value ->
						println "parameter: " + value.ParameterKey + " with Value " + value.ParameterValue + "of Type " + value.DataType;
						if (env.ConfigParameter.equalsIgnoreCase(value.ParameterKey)){
							configParameterExist = true;
						}
					}
					//fail in case the config parameter does not exist.
					if (!configParameterExist){
						error("Can't update the specified configuration parameter as it does not exist in the integration artefact.")
					}
					
					//prepare config update payload
					def putConfigPayload = '{\"ParameterValue\": \"' + "${env.NewConfigValue}" + '\", \"DataType\": \"xsd:string\"}'
					println("Updating parameter " + "${env.ConfigParameter}" + " with new value " + "${env.NewConfigValue}");
					try {
						def putConfigResp = httpRequest acceptType: 'APPLICATION_JSON',
							customHeaders: [[maskValue: false, name: 'Authorization', value: token]], 
							contentType: 'APPLICATION_JSON', 
							httpMode: 'PUT', 
							ignoreSslErrors: false, 
							requestBody: putConfigPayload, 
							responseHandle: 'LEAVE_OPEN', 
							timeout: 30, 
							url: 'https://' + "${env.CPIHost}" + '/api/v1/IntegrationDesigntimeArtifacts(Id=\'' + "${env.IntegrationFlowID}" + '\',Version=\'active\')' + '/\$links/Configurations(\'' + "${env.ConfigParameter}" + '\')';
						println("Configuration successfully updated!");
						putConfigResp.close();  
			        } catch (Exception e) {
						error("Couldn't update the configuration: \n${e}")
					}	
				}
			}
		}
    }
}
